# The following code is an implementation of official PyTorch Tutorial. 
(see https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html)

For the purpose of learning PyTorch, I've added commenets and markdowns.

If you want to install PyTorch, visit https://pytorch.org and check commands according to your environment.

My environment is composed of conda / python3.6 / CUDA 9.0 / PyTorch 0.4.1

In [4]:
#load pytorch.
import torch


The basic unit for PyTorch is called Tensor.
It is similar to NumPy's ndarrays. Tensors can be processed for GPU accelerated computing.

In [ ]:
#torch.empty makes an uninitialized matrix of tensor
x = torch.empty(5, 3)
print(x)

#complex matrices can be generated with an additional args (dim).
y = torch.empty(5, 3, 2)
print(y)

z = torch.empty(5, 3, 2, 4)
print(z)

In [12]:
#torch.rand randomly initializes a matrix
x = torch.rand(5, 3)
print(x)

tensor([[0.7408, 0.7228, 0.0717],
        [0.4122, 0.3390, 0.7992],
        [0.9049, 0.0691, 0.2008],
        [0.4692, 0.9556, 0.7041],
        [0.9409, 0.6206, 0.9505]])


In [17]:
#torch.zeros fills a matrix with zeros
x = torch.zeros(5, 3)
print(x)

#dtype = the desired data type of returned tensor
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

x = torch.zeros(5, 3, dtype=torch.float)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [19]:
#we can make a tensor from data
x = torch.tensor([5.5, 3])
print(x)

# or from numpy array
import numpy as np

x_np = np.array([3, 4, 5])
x = torch.from_numpy(x_np)
print(x)

tensor([5.5000, 3.0000])
tensor([3, 4, 5], dtype=torch.int32)


In [21]:
#it is possible to change existing tensors using new_ 
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.9339, -0.6285, -0.3859],
        [-1.9890, -1.1318,  1.2591],
        [ 0.3697, -0.5242,  0.6367],
        [ 1.0896,  0.5683,  0.7747],
        [ 0.0077, -0.1183,  0.2146]])


In [22]:
#to get the size,
print(x.size())

torch.Size([5, 3])


There are syntaxes for operations dealing with tensors. 

In [23]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-1.9105, -0.0249, -0.2131],
        [-1.4715, -0.2333,  1.5515],
        [ 1.3171, -0.0071,  1.3429],
        [ 1.1760,  1.3355,  1.2097],
        [ 0.9689,  0.7410,  1.1592]])


In [24]:
#an alternative way is
print(torch.add(x, y))

tensor([[-1.9105, -0.0249, -0.2131],
        [-1.4715, -0.2333,  1.5515],
        [ 1.3171, -0.0071,  1.3429],
        [ 1.1760,  1.3355,  1.2097],
        [ 0.9689,  0.7410,  1.1592]])


In [25]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-1.9105, -0.0249, -0.2131],
        [-1.4715, -0.2333,  1.5515],
        [ 1.3171, -0.0071,  1.3429],
        [ 1.1760,  1.3355,  1.2097],
        [ 0.9689,  0.7410,  1.1592]])


In [26]:
#in-place version: it directly changes a tensor's data
# putting _ indicates in-place methods
y.add_(x)
print(y)

tensor([[-1.9105, -0.0249, -0.2131],
        [-1.4715, -0.2333,  1.5515],
        [ 1.3171, -0.0071,  1.3429],
        [ 1.1760,  1.3355,  1.2097],
        [ 0.9689,  0.7410,  1.1592]])


In [28]:
# if you are familiar with NumPy, you may find this useful
print(y[:, 1])

tensor([-0.0249, -0.2333, -0.0071,  1.3355,  0.7410])


In [30]:
#we can change shape(or size) of tensor
x = torch.randn(4, 4)

y = x.view(16) 
y1 = x.view(16, 1) # note that these two are different!

z = x.view(-1, 8) # -1 is inferred from other dim. in this case, 2

print(x.size(), y.size(), y1.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([16, 1]) torch.Size([2, 8])


In [31]:
#in order to retrieve data, use .item()
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.1468])
0.146800234913826
